### PR TITLE
Upgrade to maplibre v4.0.0

### PR DESCRIPTION
**Pull request by dBitech**

### CODE REVIEW

**Comment by dBitech** [comment]
Unsure why the tests/test workflow is erroring, the same yarn build passes with no errors on my local machine.

**Comment by cioddi** [comment]
We definitiely need to upgrade to maplibre 4.x.
There are still some type changes and API changes that happened in MapLibre that we need to adjust to. 
Especially some functions have changed from a classic callback pattern to promises.

I have updated your branch to a point where the build is working. But still the protocol handlers need to get updated. Can you grant me access rights to your fork of the repo so I can update the branch this PR is made of?

**Comment by cioddi** [comment]
Thank you for your contribution.
I still have to go through the code tomorrow but so far everything looks fine.
So I think we can merge and make a Release soon. This should become the 1.0.0 release since it includes breaking API changes (not in MapComponents but in MapLibre).

**Comment by cioddi** [comment]
The only issue I encountered was the TerrainLayer example is slightly moving the viewport when zooming out. Since the issue appears to be upstream and the feature also is still experimental I will merge this now.

**Pull request merged**
